Question.create!(text: "Which of these might be used in underwater naval operations?", answers: { a: "Frogmen", b: "Newtmen", c: "Toadmen", d: "Tadpolemen"}, correct_answer: "a")
Question.create!(text: "Which of these kills its victims by constriction?", answers: { a: "Andalucia", b: "Anaconda", c: "Andypandy", d: "Annerobinson"}, correct_answer: "b")
Question.create!(text: "Which disease devastated livestock across the UK during 2001?", answers: { a: "Hand-and-foot", b: "Foot-in-mouth", c: "Hand-to-mouth", d: "Foot-and-mouth"}, correct_answer: "d")
Question.create!(text: "Which of the following is most likely to cause a rise in the average temperature of earth's atmosphere in future?", answers: { a: "Atomic warfare", b: "CO2 from fossil fuels", c: "Dust clouds from valcanoes", d: "Depletion of earth's ozone layer"}, correct_answer: "b")
Question.create!(text: "Which of the following elements is a metal?", answers: { a: "S", b: "Se", c: "I", d: "Ga"}, correct_answer: "d")
Question.create!(text: "Which of the following items will be attracted to the north pole of a permanent magnet by a magnet force?", answers: { a: "The north pole of another permanent magnet", b: "A piece of iron that is not a permanent magnet", c: "A positively charged glass rod", d: "A negatively charged rubber rod"}, correct_answer: "b")
Question.create!(text: "The fastest-running terrestrial animal is", answers: { a: "cheetah", b: "Jaguar", c: "human", d: "lion"}, correct_answer: "a")
Question.create!(text: "As you go down into a well, your weight", answers: { a: "increases slightly", b: "decreases slightly", c: "remains exactly the same", d: ")None of the above"}, correct_answer: "b")
Question.create!(text: "Which prefix is often used with scientific terms to indicate that something is the same, equal or constant?", answers: { a: "Iso", b: "Mega", c: "Meta", d: "quasi"}, correct_answer: "a")
Question.create!(text: "Yeast, used in making bread is a", answers: { a: "fungus", b: "bacteria", c: "plant", d: "Seed"}, correct_answer: "a")
Question.create!(text: "A gas used as a disinfectant in drinking water is", answers: { a: "Hydrogen", b: "Oxygen", c: "Fluorine", d: "Chlorine"}, correct_answer: "d")
Question.create!(text: "Brass gets discoloured in air because of the presence of which of the following gases in air?", answers: { a: "Oxygen", b: "Hydrogen sulphide", c: "Carbon dioxide", d: "Nitrogen"}, correct_answer: "b")
Question.create!(text: "Which of the following is a non metal that remains liquid at room temperature?", answers: { a: "Phosphorous", b: "Bromine", c: "Chlorine", d: "Helium"}, correct_answer: "b")
Question.create!(text: "Which of the following is used in pencils?", answers: { a: "Graphite", b: "Silicon", c: "charcoal", d: "phophoras"}, correct_answer: "a")
Question.create!(text: "Chemical formula for water is", answers: { a: "NaAlO2", b: "H2O", c: "Al2O3", d: "CaSiO3"}, correct_answer: "b")
Question.create!(text: "The gas usually filled in the electric bulb is", answers: { a: "nitrogen", b: "hydrogen", c: "carbon dioxide", d: "oxygen"}, correct_answer: "a")
Question.create!(text: "Washing soda is the common name for", answers: { a: "Sodium carbonate", b: "Calcium bicarbonate", c: "Sodium bicarbonate", d: "Calcium carbonate"}, correct_answer: "a")
Question.create!(text: "Which of the gas is not known as green house gas?", answers: { a: "Methane", b: "Nitrous oxide", c: "Carbon dioxide", d: "Hydrogen"}, correct_answer: "d")
Question.create!(text: "Light year is a unit of", answers: { a: "time", b: "distance", c: "intensity of light", d: "Light"}, correct_answer: "b")
Question.create!(text: "Bromine is a", answers: { a: "black solid", b: "red liquid", c: "colourless gas", d: "highly inflammable gas"}, correct_answer: "b")
Question.create!(text: "The hardest substance available on earth is", answers: { a: "Gold", b: "Iron", c: "Diamond", d: "Platinum"}, correct_answer: "c")
Question.create!(text: "Which of the following is an example of an optical disk?", answers: { a: "Memory disk", b: "Magnetic disk", c: "Hard disk", d: "digital versatile disk"}, correct_answer: "d")
Question.create!(text: "Which of the following is(are) an example of storage devices?", answers: { a: "tapes", b: "dvds", c: "magnetic disk", d: "all of them"}, correct_answer: "d")
Question.create!(text: "Which of the following is not an example of Operating System ?", answers: { a: "Microsoft office", b: "Windows", c: "Linux", d: "dunix"}, correct_answer: "a")
Question.create!(text: "Reusable optical storage will typically have the acronym", answers: { a: "RW", b: "RAM", c: "none of them", d: "both"}, correct_answer: "a")
Question.create!(text: "orel Draw is a popular", answers: { a: "Illustration programme", b: "Programming language", c: "Text programme", d: "None of the above"}, correct_answer: "a")
Question.create!(text: "Firewalls are used to protect a communication network system against", answers: { a: "Unauthorized attacks", b: "Virus attacks", c: "Data-driven attacks", d: "Fire-attacks"}, correct_answer: "a")
Question.create!(text: "RAM means", answers: { a: "Random Access Memory", b: "Rigid Access Memory", c: "Rapid Access Memory", d: "Revolving Access Memory"}, correct_answer: "a")
Question.create!(text: "Which of the following is type of LAN ?", answers: { a: "Ethernet", b: "Token Ring", c: "FDDI", d: "All of the above"}, correct_answer: "d")
Question.create!(text: "Internet explorer is a type of", answers: { a: "Operating System", b: "Compiler", c: "Browser", d: "IP address"}, correct_answer: "c")
Question.create!(text: "The file extension of MS-Word document in Office 2007 is .................", answers: { a: ".pdf", b: ".doc", c: ".docx", d: ".txt"}, correct_answer: "c")
Question.create!(text: "Ozone hole refers to", answers: { a: "hole in ozone layer", b: "decrease in the ozone layer in troposphere", c: "decrease in thickness of ozone layer in stratosphere", d: "increase in the thickness of ozone layer in troposphere"}, correct_answer: "c")
Question.create!(text: "Question 1. The average of first 50 natural numbers is …………. .", answers: { a: "25.3", b: "25.5", c: "25", d: "12.25"}, correct_answer: "b")
