Question.create!(text: "Which of these might be used in underwater naval operations?", answers: { a: "Frogmen", b: "Newtmen", c: "Toadmen", d: "Tadpolemen"}, correct_answer: "a")
Question.create!(text: "Which of these kills its victims by constriction?", answers: { a: "Andalucia", b: "Anaconda", c: "Andypandy", d: "Annerobinson"}, correct_answer: "b")
Question.create!(text: "Which disease devastated livestock across the UK during 2001?", answers: { a: "Hand-and-foot", b: "Foot-in-mouth", c: "Hand-to-mouth", d: "Foot-and-mouth"}, correct_answer: "d")
Question.create!(text: "A?", answers: { a: "a", b: "b", c: "c", d: "d"}, correct_answer: "a")
Question.create!(text: "B?", answers: { a: "a", b: "b", c: "c", d: "d"}, correct_answer: "b")
Question.create!(text: "C?", answers: { a: "a", b: "b", c: "c", d: "d"}, correct_answer: "c")
Question.create!(text: "D?", answers: { a: "a", b: "b", c: "c", d: "d"}, correct_answer: "d")
Question.create!(text: "E?", answers: { a: "e", b: "b", c: "c", d: "d"}, correct_answer: "a")
Question.create!(text: "F?", answers: { a: "f", b: "b", c: "c", d: "d"}, correct_answer: "a")
Question.create!(text: "G?", answers: { a: "g", b: "b", c: "c", d: "d"}, correct_answer: "a")
